/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.ibm.watson.developer_cloud.visual_recognition.v3.*;
import com.ibm.watson.developer_cloud.service.model.GenericModel.*;
import com.ibm.watson.developer_cloud.visual_recognition.v3.model.ClassifyOptions;

import java.io.IOException;
import java.io.InputStream;
import java.io.FileInputStream;


public class App {

    public String getGreeting() {
        return "Hello World!";
    }
    
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        VisualRecognition service = new VisualRecognition(VisualRecognition.VERSION_DATE_2016_05_20);
        service.setApiKey("a4663f77201e547faeca597dc27eed2cd0f4cf77");
        
        try {
            InputStream stream = new FileInputStream("./out/production/resources/sudoku_image.jpg");
            ClassifyOptions classifyOptions = new ClassifyOptions().Builder()
                    .imagesFile(stream)
                    .imagesFileName("sukoku.jpg")
                    .parameters()
                    .build();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
